In [66]:
import pandas as pd

loc = "fallcampdata/EarthCrisisData.xlsx"
df = pd.read_excel(loc)

headers = list(df.columns.values)
headers[0] = 'year'
headers[1] = 'waste'
df.columns = headers
df.head()

   year  waste
0  1990  19358
1  1991  19484
2  1992  20293
3  1993  21499
4  1994  23561

In [67]:
import statsmodels.formula.api as sm
result = sm.ols(formula='waste ~ year',data=df).fit()
result.summary()

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/statsmodels/stats/stattools.py:72: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  waste   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.856
Method:                 Least Squares   F-statistic:                     24.82
Date:                Sat, 29 Sep 2018   Prob (F-statistic):             0.0155
Time:                        16:11:17   Log-Likelihood:                -38.290
No. Observations:                   5   AIC:                             80.58
Df Residuals:                       3   BIC:                             79.80
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -2.055e+06   4.17e+05     -4.932      0.016   -3.38e+06   -7.29e+05
year        1042.1000    209.178      4.982      0.016     376.403    1707.797
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.494
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.763
Skew:                           0.342   Prob(JB):                        0.683
Kurtosis:                       1.212   Cond. No.                     2.81e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.81e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [68]:
import pandas as pd

loc = "SalesIQData.xlsx"

df = pd.read_excel(loc)

df.head()

   Sales Person  Intelligence  Extroversion  $ Sales/Week
0             1            89            21          2625
1             2            93            24          2700
2             3            91            21          3100
3             4           122            23          3150
4             5           115            27          3175

In [69]:
df.columns = ["salesman", "int", "extrovert", "salesdollars"]
df.head()

   salesman  int  extrovert  salesdollars
0         1   89         21          2625
1         2   93         24          2700
2         3   91         21          3100
3         4  122         23          3150
4         5  115         27          3175

In [70]:
df.corr()

              salesman       int  extrovert  salesdollars
salesman      1.000000 -0.076449   0.061884     -0.099698
int          -0.076449  1.000000  -0.136584      0.247577
extrovert     0.061884 -0.136584   1.000000      0.548017
salesdollars -0.099698  0.247577   0.548017      1.000000

In [71]:
import statsmodels.formula.api as sm

#result = sm.ols(formula='waste ~ year',data=df).fit()
#result.summary()

result = sm.ols(formula='salesdollars~ int + extrovert - 1', data=df).fit()
result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           salesdollars   R-squared:                       0.989
Model:                            OLS   Adj. R-squared:                  0.988
Method:                 Least Squares   F-statistic:                     821.2
Date:                Sat, 29 Sep 2018   Prob (F-statistic):           2.07e-18
Time:                        16:11:18   Log-Likelihood:                -143.29
No. Observations:                  20   AIC:                             290.6
Df Residuals:                      18   BIC:                             292.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
int           10.5963      2.585      4.098      0.001       5.164      16.028
extrovert     80.2640     12.541      6.400      0.000      53.916     106.612
==============================================================================
Omnibus:                        1.635   Durbin-Watson:                   2.146
Prob(Omnibus):                  0.442   Jarque-Bera (JB):                0.565
Skew:                          -0.378   Prob(JB):                        0.754
Kurtosis:                       3.326   Cond. No.                         19.6
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [72]:
import pandas as pd

loc="fallcampdata/TamiamiTamalesData.xlsx"

df = pd.read_excel(loc)
df = df.dropna()
df.head()

,Cart Location,Hot Dog Sales,Employees in Nearby Office Buildings,Num of Nearby Restaurants,Num of Other Food Carts Nearby,Price
0,1.0,100,1600.0,8.0,12.0,4.1600
1,2.0,80,1200.0,6.0,13.0,4.6325
2,3.0,450,2800.0,19.0,6.0,0.5000
3,4.0,580,4300.0,19.0,2.0,0.4700
4,5.0,100,1400.0,6.0,13.0,4.2400

In [73]:
df.columns = ["loc", "sales", "emp", "rest", "othcrt", "price"]
df.head()

   loc  sales     emp  rest  othcrt   price
0  1.0    100  1600.0   8.0    12.0  4.1600
1  2.0     80  1200.0   6.0    13.0  4.6325
2  3.0    450  2800.0  19.0     6.0  0.5000
3  4.0    580  4300.0  19.0     2.0  0.4700
4  5.0    100  1400.0   6.0    13.0  4.2400

In [74]:
df.corr()

             loc     sales       emp      rest    othcrt     price
loc     1.000000  0.042705 -0.068923  0.049701  0.077219 -0.138905
sales   0.042705  1.000000  0.943238  0.913674 -0.919762 -0.966406
emp    -0.068923  0.943238  1.000000  0.856976 -0.874692 -0.881498
rest    0.049701  0.913674  0.856976  1.000000 -0.761793 -0.933867
othcrt  0.077219 -0.919762 -0.874692 -0.761793  1.000000  0.860278
price  -0.138905 -0.966406 -0.881498 -0.933867  0.860278  1.000000

In [75]:
import statsmodels.formula.api as sm
#result = sm.ols(formula='waste ~ year',data=df).fit()
mod = sm.ols(formula = ' sales ~ emp + rest + othcrt + price', data=df).fit()
mod.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.981
Model:                            OLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     314.9
Date:                Sat, 29 Sep 2018   Prob (F-statistic):           5.46e-21
Time:                        16:11:18   Log-Likelihood:                -138.10
No. Observations:                  30   AIC:                             286.2
Df Residuals:                      25   BIC:                             293.2
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    319.4599     61.182      5.221      0.000     193.454     445.466
emp            0.0560      0.015      3.802      0.001       0.026       0.086
rest           3.1105      2.981      1.044      0.307      -3.028       9.249
othcrt        -9.2204      2.695     -3.421      0.002     -14.772      -3.669
price        -47.9633     11.080     -4.329      0.000     -70.782     -25.144
==============================================================================
Omnibus:                        0.143   Durbin-Watson:                   2.492
Prob(Omnibus):                  0.931   Jarque-Bera (JB):                0.361
Skew:                          -0.014   Prob(JB):                        0.835
Kurtosis:                       2.463   Cond. No.                     2.81e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.81e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [76]:
import statsmodels.formula.api as sm
#result = sm.ols(formula='waste ~ year',data=df).fit()
mod1 = sm.ols(formula = ' sales ~ emp + rest + othcrt + price - 1', data=df).fit()
mod1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.987
Model:                            OLS   Adj. R-squared:                  0.986
Method:                 Least Squares   F-statistic:                     513.5
Date:                Sat, 29 Sep 2018   Prob (F-statistic):           2.52e-24
Time:                        16:11:19   Log-Likelihood:                -149.16
No. Observations:                  30   AIC:                             306.3
Df Residuals:                      26   BIC:                             311.9
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
emp            0.0970      0.018      5.494      0.000       0.061       0.133
rest          11.9860      3.471      3.453      0.002       4.851      19.121
othcrt        -5.6241      3.695     -1.522      0.140     -13.219       1.970
price         -9.0656     11.628     -0.780      0.443     -32.967      14.836
==============================================================================
Omnibus:                        0.709   Durbin-Watson:                   1.867
Prob(Omnibus):                  0.702   Jarque-Bera (JB):                0.704
Skew:                           0.073   Prob(JB):                        0.703
Kurtosis:                       2.264   Cond. No.                     3.98e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.98e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [77]:
import statsmodels.formula.api as sm
#result = sm.ols(formula='waste ~ year',data=df).fit()
mod2 = sm.ols(formula = ' sales ~ emp + othcrt + price - 1', data=df).fit()
mod2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.980
Method:                 Least Squares   F-statistic:                     484.6
Date:                Sat, 29 Sep 2018   Prob (F-statistic):           1.40e-23
Time:                        16:11:19   Log-Likelihood:                -154.83
No. Observations:                  30   AIC:                             315.7
Df Residuals:                      27   BIC:                             319.9
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
emp            0.1557      0.006     27.187      0.000       0.144       0.167
othcrt         2.7994      3.288      0.851      0.402      -3.948       9.547
price        -35.0245     10.513     -3.332      0.003     -56.596     -13.453
==============================================================================
Omnibus:                        3.689   Durbin-Watson:                   2.129
Prob(Omnibus):                  0.158   Jarque-Bera (JB):                1.542
Skew:                          -0.083   Prob(JB):                        0.463
Kurtosis:                       1.902   Cond. No.                     2.97e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.97e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [78]:
import statsmodels.formula.api as sm
#result = sm.ols(formula='waste ~ year',data=df).fit()
mod3 = sm.ols(formula = ' sales ~ emp + othcrt + price', data=df).fit()
mod3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  sales   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.977
Method:                 Least Squares   F-statistic:                     418.1
Date:                Sat, 29 Sep 2018   Prob (F-statistic):           4.15e-22
Time:                        16:11:19   Log-Likelihood:                -138.74
No. Observations:                  30   AIC:                             285.5
Df Residuals:                      26   BIC:                             291.1
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    355.8724     50.343      7.069      0.000     252.390     459.354
emp            0.0616      0.014      4.482      0.000       0.033       0.090
othcrt        -8.1553      2.499     -3.264      0.003     -13.292      -3.019
price        -56.9426      6.993     -8.143      0.000     -71.316     -42.569
==============================================================================
Omnibus:                        0.059   Durbin-Watson:                   2.620
Prob(Omnibus):                  0.971   Jarque-Bera (JB):                0.228
Skew:                           0.085   Prob(JB):                        0.892
Kurtosis:                       2.609   Cond. No.                     2.30e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.3e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""